#! /bin/bash

## Source: https://docs.microsoft.com/en-us/windows/win32/menurc/using-rc-the-rc-command-line-
#/?: Help
#/c: Codepage
#/d: Defines
#/fm <mresname>: Create neutral .res and language dependent .mui
#/fo <resname>: output file
#/g1: 
#/h: like /?
#/i: include dir
#/j <loctype>: localizable types
#/k <overtype>:
#/l <langid>: language id /l0x409 == en_us
#/n: null terminates all string
#/q: 

while [ $# -gt 1 ]; do
  param=$1
  shift
  case "$param" in
    -D* ) defines="$defines $param";;
    /fo*) output=${param#/fo};;
    /l* ) language=${param#/l};;
    *) ;;
  esac
done

input="$1"
[ -z "$output" ] && output="${input%.rc}.res"

#/l0x409 -DGOOGLE_PROTOBUF_CMAKE_BUILD -D_CRT_SECURE_NO_WARNINGS /foCMakeFiles/libprotobuf-lite.dir/version.rc.res /home/nemir/goldberg_emulator_cmake/protobuf/win32/protobuf-src/cmake/version.rc

echo "Input file : $input"
echo "Output file: $output"
echo "Language   : $language"
echo "Defines    : $defines"

x86_64-w64-mingw32-windres -l "$language" $defines -i "$input" -o "$output"
